<script type="text/javascript">
	$(document).ready(function() {
		$('#savePassword').on('click', function () {
		var oldPassword = $('#oldPassword').val();
		var newPassword = $('#newPassword').val();
		var newPasswordRepeat = $('#newPasswordRepeat').val();
		if(newPassword == newPasswordRepeat && newPassword.length != 0) {
			$('.spinner-action').show();
			$('#newPasswordRepeat').css('border', '1px solid #ccc');
			$.ajax({
		      type: "POST",
		      url: "/profile/checkpasswordajax",
		      dataType : 'json',
		      data : {		        
		        password: oldPassword		           
		      },
		      success: function(json)
		      {
		        if(json['wynik'] == "succes") {
		        	$.ajax({
				      type: "POST",
				      url: "/profile/saveuserajax",
				      dataType : 'json',
				      data : {				        
				        password: newPasswordRepeat    
				      },
				      success: function(json)
				      {
				        if(json['wynik'] == "succes") {			        	        	
				        	$('.spinner-action').fadeOut();
							$('#oldPassword').val('');
							$('#newPassword').val('');
							$('#newPasswordRepeat').val('');
				        } 
				      },
				      error: function(data){
				      		console.log(data);
				        //alert("fatal registration error"); 		        
				      }
				    });	 
		        } else {
					$('.spinner-action').fadeOut();
		        	$('#oldPassword').css('border', '1px solid red');
		        }
		      },
		      error: function (data) {
		      	console.log(data);
		      }
		    });	
		} else {
			$('#newPasswordRepeat').css('border', '1px solid red');
		}
	});
	});

</script>
	<div class="modal-header">
            <h3>Zmiana hasła</h3>
			<div class="spinner-action"><img src="/img/ajax-loader.gif" /></div>
    </div>
    <div class="modal-body" style="background:rgb(250, 250, 250); max-height:none;">
		<div class="col-md-4">
			<p class="help-block"><label for="oldPassword">Stare hasło: </label></p>
			<input type="password" name="oldPassword" id="oldPassword" class="form-control" /> <br>
			<p class="help-block"><label for="newPassword">Nowe hasło: </label></p>
			<input type="password" name="newPassword" id="newPassword" class="form-control" /> <br>
			<p class="help-block"><label for="newPasswordRepeat">Powtórz nowe hasło: </label></p>
			<input type="password" name="newPasswordRepeat" id="newPasswordRepeat" class="form-control" /> <br>
		</div>
	</div>
	<div class="modal-footer">
		<button class='btn' type='button' onClick="window.location.href='/profile'">Anuluj</button>
		<button class='btn btn-primary' type='button' id="savePassword">Zapisz</button>
    </div>