<?php $this->headScript()->appendFile('/js/jquery.uploadify.js'); ?>
<?php $this->headLink()->appendStylesheet('/css/uploadify.css'); ?>
<?php $timestamp = time(); $path_parts = pathinfo(getcwd()); ?>
<?php $this->headLink()->appendStylesheet('/css/profile.css'); ?>
<script>
	$(document).ready(function () {
		String.prototype.escapeDiacritics = function()
		{
			return this.replace(/ą/g, 'a').replace(/Ą/g, 'A')
				.replace(/ć/g, 'c').replace(/Ć/g, 'C')
				.replace(/ę/g, 'e').replace(/Ę/g, 'E')
				.replace(/ł/g, 'l').replace(/Ł/g, 'L')
				.replace(/ń/g, 'n').replace(/Ń/g, 'N')
				.replace(/ó/g, 'o').replace(/Ó/g, 'O')
				.replace(/ś/g, 's').replace(/Ś/g, 'S')
				.replace(/ż/g, 'z').replace(/Ż/g, 'Z')
				.replace(/ź/g, 'z').replace(/Ź/g, 'Z');
		}
		if($('#Zdjecie').val() != 0) {
			$('.img-rounded').attr('src', '/img/employee/' + $('#Zdjecie').val());
		}
		$('#file_upload').uploadify({
			'checkExisting' : '/profile/checkExistPhotoAjax',
			'multi'    : false,
			'fileTypeExts' : '*.jpg; *.png',
			'formData'     : {
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
			},
			'swf'      : '/uploadify.swf',
			'uploader' : '/profile/uploadPhotoEmployeeAjax',
			'onUploadSuccess' : function(file, data, response) {
				$('#queue').show();
				$('#file_upload').hide();
				FileName = file.name.escapeDiacritics();
				$('.img-rounded').attr('src', '/img/employee/' + FileName);
			}
		});
		var FileName;
		$('#saveSettings').click(function () {
			var aImie = $('#Imie').val();
			var aNazwisko = $('#Nazwisko').val();
			var aEmail = $('#Email_user').val();
			var aTelefon = $('#Telefon').val();
			if(FileName) {
				var aZdjecie = FileName;
			} else {
				var aZdjecie = $('.img-rounded').attr('src').slice(14, $('.img-rounded').attr('src').lenght);
			}
			var aAdres = $('#Adres').val();
			if(!aZdjecie) { aZdjecie = ''; }
			if(!aAdres) { aAdres = ''; }
			if(!aImie) { $('#Imie').next().fadeIn(); aImieOk = 0; } else { $('#Imie').next().fadeOut(); aImieOk = 1; }
			if(!aNazwisko) { $('#Nazwisko').next().fadeIn(); aNazwiskoOk = 0; } else { $('#Nazwisko').next().fadeOut(); aNazwiskoOk = 1; }
			var WzorMaila = /^[0-9a-z_.-]+@[0-9a-z.-]+\.[a-z]{2,3}$/i
			var WzorTelefon = /^\d{3}-\d{3}-\d{3}$/i
			if(!aEmail) { 
				$('#Email_user').next().fadeIn(); aEmailOk = 0; 
			} else { 
				if (!WzorMaila.test(aEmail)) {
					$('#Email_user').next().text('*wprowadź poprawny adres').fadeIn();
					aEmailOk = 0;
				} else {
					aEmailOk = 1;
					$('#Email_user').next().fadeOut().text('*uzupełnij to pole');
				}
			}
			if(!aTelefon) { 
				$('#Telefon').next().fadeIn(); aTelefonOk = 0; 
			} else { 
				if (!WzorTelefon.test(aTelefon)) {
					$('#Telefon').next().text('*użyj formatu: 888-999-777').fadeIn();
					aTelefonOk = 0;
				} else {
					aTelefonOk = 1;
					$('#Telefon').next().fadeOut().text('*uzupełnij to pole');
				} 
			}
			if(aImieOk == 1 && aNazwiskoOk == 1 && aEmailOk == 1 && aTelefonOk == 1) {
				$('.spinner-action').fadeIn();
				//alert(aImie + ' ' + aNazwisko+ ' ' +aEmail+ ' ' +aTelefon+ ' ' +aZdjecie+ ' ' +aAdres+ ' ' +param);
				var aId_user = $('#idUser').val();
				$.ajax({
					type: "POST",
					url: "/profile/editEmployeeAjax",
					dataType : 'json',
					data : {
						sId_user : aId_user,
						sImie : aImie,
						sNazwisko : aNazwisko,
						sEmail : aEmail,
						sTelefon : aTelefon,
						sZdjecie : aZdjecie,
						sAdres : aAdres
					},
					success: function(json)
					{
						if(json['wynik']) {
							$('.spinner-action').fadeOut();
							window.location.href = "/profile";
						}
					},
					error: function(data){
						alert("fatal error"); 
					}
				});
			}
		});
	});
</script>
<?php
	$form = $this->form;
	$form->prepare();
	echo $this->form()->openTag($form);
?>
	<input type="hidden" id="Zdjecie" value="<?php echo $this->photo; ?>" />
	<input type="hidden" id="idUser" value="<?php echo $this->id; ?>" />
	<div class="modal-header">
            <h3>Ustawienia </h3>
			<div class="spinner-action"><img src="/img/ajax-loader.gif" /></div>
    </div>
    <div class="modal-body" style="background:rgb(250, 250, 250); max-height:none;">
		 <div class="col-md-4">
			<div class="logowrapper" style="text-align: center; margin-top: 15px;"><img class="img-rounded" src="http://www.placehold.it/140x140" /></div>
         </div>
         <div class="col-md-4">
              <p class="help-block"><?php echo $this->formLabel($form->get('imie')); ?></p>
              <?php echo $this->formInput($form->get('imie')); ?>
			  <div class="error-validate"> *uzupełnij to pole </div>
			  <p class="help-block"><?php echo $this->formLabel($form->get('telefon')); ?></p>
              <?php echo $this->formInput($form->get('telefon')); ?>
			  <div class="error-validate"> *uzupełnij to pole </div>
			  <p class="help-block" style="margin-top:9.5px;"><label>Zmień zdjęcie:</label></p>
			  <div id="queue"></div>
			  <input id="file_upload" name="file_upload" type="file" multiple="false" accept="image/*" />
		 </div>
		 <div class="col-md-4">				
			 <p class="help-block"><?php echo $this->formLabel($form->get('nazwisko')); ?></p>
             <?php echo $this->formInput($form->get('nazwisko')); ?>
			 <div class="error-validate"> *uzupełnij to pole </div>
             <p class="help-block"><?php echo $this->formLabel($form->get('email')); ?></p>
             <?php echo $this->formInput($form->get('email')); ?>
			 <div class="error-validate"> *uzupełnij to pole </div>
		</div>	 
		<div class="col-md-8 pull-right">
			<p class="help-block"><?php echo $this->formLabel($form->get('adres')); ?></p>
             <?php echo $this->formInput($form->get('adres')); ?>
		</div>
</div>
	<div class="modal-footer">
		<button class='btn' type='button' onClick="window.location.href='/profile'">Anuluj</button>
		<button class='btn btn-primary' type='button' id="saveSettings">Zapisz</button>
    </div>
<?php echo $this->form()->closeTag(); ?>