<?php $this->headLink()->appendStylesheet('/css/video.css'); ?>
<?php $this->headScript()->appendFile('/js/video.js'); ?>
<div class="well">
	<div class="row">
		<div class="col-md-12">
		    <h3 class="pull-left">Video</h3>
			<div class="spinner-action pull-right"><img src="/img/ajax-loader.gif" /></div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<iframe width="560" height="315" class="youtube" src="http://www.youtube.com/embed/<?php echo $this->description; ?>" frameborder="0" allowfullscreen></iframe>
		</div>
		<div class="col-md-6">
			<p class="help-block"><span class="required">*</span><?php echo $this->formLabel($form->get('link')); ?></p>
        	<?php echo $this->formInput($form->get('link')); ?>
        	<div class="error-validate"> *uzupełnij to pole </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 marginTop">
		<i class="pull-left"> pola oznaczone <span class="red">*</span> są polami obowiązkowymi </i>
		<div class="pull-right">
			<button class='btn' type='button' onClick="window.location.href='/admin/video'">Wyjdź</button>
			<button class='btn btn-primary' type='button' id="saveEditVideo">Zapisz</button>
		</div>
	</div>
	</div>
</div>