<section id="popup2">
	<div id="popup2-header">
		<h3>Rejestracja</h3>
		<span href="#" class="popup2-close"></span>		
	</div>
	<div id="popup2-content">
		<div id="form">
			<?php
				$form = $this->form;
				
				$form->prepare();

				echo $this->form()->openTag($form);
			?>
			<div class="input">
				<?php echo $this->formLabel($form->get('login')); ?>
				<?php echo $this->formInput($form->get('login')); ?>
			</div>
			<div class="input last" id="error1">
				
			</div>
			<div class="input">
				<?php echo $this->formLabel($form->get('email')); ?>
				<?php echo $this->formInput($form->get('email')); ?>
			</div>
			<div class="input last" id="error2">
				
			</div>
			<div class="input">
				<?php echo $this->formLabel($form->get('password')); ?>
				<?php echo $this->formInput($form->get('password')); ?>
			</div>
			<div class="input last" id="error3">
				
			</div>
			<div class="input">
				<?php echo $this->formLabel($form->get('password_confirm')); ?>
				<?php echo $this->formInput($form->get('password_confirm')); ?>
			</div>
			<div class="input last" id="error4">
				
			</div>
			<div class="verification">
				<div id="vimage">
					<div id="number">Wybierz obrazek: <span id="randNumber"></span></div>
					<div class="pictures">
						<ul>
							<li><img src="<?php $this->basePath() ?>/img/captcha/0.png"/></li>
							<li><img src="<?php $this->basePath() ?>/img/captcha/1.png"/></li>
							<li><img src="<?php $this->basePath() ?>/img/captcha/2.png"/></li>
							<li><img src="<?php $this->basePath() ?>/img/captcha/3.png"/></li>
							<li><img src="<?php $this->basePath() ?>/img/captcha/4.png"/></li>
						</ul>
					</div>
				</div>
				<span id="error5">
					
				</span>				
				<?php //echo $this->formSubmit($form->get('submit')); ?>
				<a  id="send-message" href="#">zarejestruj się</a>
				<span id="load">
					
				</span>
			</div>
			<?php echo $this->form()->closeTag(); ?>
			
			<div style="clear:both"></div>
		</div>
	</div>
	<div id="content1">
		Dziękujemy za rejestrację.
		Na podany adres email została wysłana wiadomość. Potwierdź rejestrację i zostań volley-masterem!
		<div style="clear:both"></div>
	</div>
</section>




