<?php $this->headScript()->appendFile('/js/login.js'); ?>
<?php $this->headLink()->appendStylesheet('/css/login.css') ?>
    <div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Logowanie</div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#" data-toggle="modal" data-target="#myModal">Zapomniałeś hasła?</a></div>
                    </div>     

                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                        <form>
                            
                       
                                    
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <?php echo $this->formElement($form->get('login'));?>                              
                                    </div>
                                
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                         <?php echo $this->formElement($form->get('password'));?>
                                        
                                    </div>
                                    

                                
                          


                                <div style="margin-top:10px" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls login-modify text-right">
                                    	<img class="login-spinner" src="/img/295.gif" />
                                    	<a id="btn-login" href="#" class="btn btn-success">Zaloguj  </a>
                                      
                                      

                                    </div>
                                </div>


                                
                            </form>     



                        </div>                     
                    </div>  
        </div>
     
    </div>

<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Podaj email</h4>
      </div>
      <div class="modal-body">
      	<div id="error3-log"></div>
       <div class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                                        <input id="mail" type="password" class="form-control" name="mail" placeholder="e-mail">
                                    </div>
      </div>
      <div class="modal-footer">
        <img class="load2" src="/img/295.gif" />
        <button type="button" class="btn btn-primary button2-log">Wyślij</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->