<?php $this->headLink()->appendStylesheet('/css/offer.css'); ?>
<div class="well">
<div class="row">
	<div class="col-md-12">
	    <h3 class="pull-left">Regulamin</h3>		
	</div>
</div>



<div class="row " >
	<div class="desc" style="text-align: justify;">	
		<div class="col-md-12">			
			<?php echo $statute->description_1 ?>	
		</div>									
	</div>
	<div class="col-md-12">
		<div class="pull-right">
			<button class='btn btn-primary' style="margin-top: 10px;"  type='button' onClick="window.location.href='/admin/statute/edit'">Edytuj</button>
		</div>
	</div>
</div>

</div>
