<h1>Index = Retrieve</h1>
<a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'create')); ?>">Create</a>
<table>
<tr>
	<th>id</th>
	<th>login</th>
	<th>email</th>
</tr>
<?php
	foreach ($rowset as $row) {
?>
		<tr>
			<td><?php  echo $row['id']; ?></td>
			<td><?php  echo $row['login']; ?></td>
			<td><?php  echo $row['email']; ?></td>
			<td><a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'update', 'id' => $row['id'])); ?>">Edit</a></td>
			<td><a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'delete', 'id' => $row['id']));?>" onclick="return confirm('Do you rely want to delete the record;')">Delete</a></td>
		</tr>
<?php
	}
?>
</table>