<?php $this->headLink()->appendStylesheet('/css/offer.css'); ?>
<div class="well">
<div class="row">
	<div class="col-md-12">
	    <h3 class="pull-left">Karwia</h3>		
	</div>
</div>



<div class="row " >
	<div class="desc" style="text-align: justify;">			
		<img src="/img/extra/<?php echo $extra->image ?>" align="left" alt="" class="img-responsive img-inline aaa karwia-image offer-image">					
		<?php echo $extra->description_1 ?>										
	</div>
	<div class="col-md-12">
		<div class="pull-right">
			<button class='btn btn-primary' style="margin-top: 10px;"  type='button' onClick="window.location.href='/admin/extra/edit'">Edytuj</button>
		</div>
	</div>
</div>

</div>
